# Use an official OpenJDK 17 runtime with slim-buster tag
FROM openjdk:17-jdk-slim

# Set the working directory to /app
WORKDIR /app

# Copy the Spring Boot JAR file into the container
COPY target/demo-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose the port your Spring Boot application will listen on
EXPOSE 8080

# Define the command to run your application
CMD ["java", "-jar", "app.jar"]
